import type { ReactNode } from "react";

export function Metric({ label, value, detail }: { label: string; value: string; detail?: string }) {
  return <section className="metric"><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</section>;
}

export function DataTable({ rows, columns, action }: { rows: any[]; columns: string[]; action?: (row: any) => ReactNode }) {
  if (!rows.length) return <div className="empty">暂无记录</div>;
  return (
    <div className="table-wrap">
      <table>
        <thead><tr>{columns.map((column) => <th key={column}>{columnLabel(column)}</th>)}{action && <th className="table-actions-head">操作</th>}</tr></thead>
        <tbody>
          {rows.map((row, index) => (
            <tr key={row.id ?? index}>{columns.map((column) => <td key={column}>{cell(row[column])}</td>)}{action && <td className="table-actions-cell">{action(row)}</td>}</tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

const columnLabels: Record<string, string> = {
  id: "ID",
  metric: "指标",
  value: "数值",
  label: "名称",
  target_view: "目标页面",
  email: "邮箱",
  display_name: "显示名称",
  user_type: "用户类型",
  email_verified_at: "邮箱验证时间",
  status: "状态",
  balance: "余额",
  reserved_balance: "预留余额",
  currency: "币种",
  updated_at: "更新时间",
  api_key_count: "密钥数",
  total_usage_cost: "总用量成本",
  created_at: "创建时间",
  name: "名称",
  display_prefix: "显示前缀",
  model_scope: "模型范围",
  ip_allowlist: "IP 白名单",
  last_used_at: "最后使用",
  entry_type: "类型",
  amount: "金额",
  amount_usd: "金额 USD",
  balance_after: "变动后余额",
  reserved_after: "变动后预留",
  reference_type: "引用类型",
  grant_value: "赠送金额",
  max_claims: "最大领取",
  claim_count: "领取次数",
  expires_at: "过期时间",
  wallet_ledger_id: "钱包流水 ID",
  claimed_at: "领取时间",
  model_name: "模型名称",
  provider_hint: "供应商提示",
  aliases: "别名",
  endpoint_capabilities: "端点能力",
  pricing: "价格",
  effective_pricing: "有效价格",
  billing_multiplier: "计费倍率",
  description: "描述",
  icon: "图标",
  tags: "标签",
  vendor: "厂商",
  pricing_version: "价格版本",
  supported_endpoint_types: "支持端点",
  available_endpoints: "可用端点",
  public_visible: "公开可见",
  provider_name: "供应商",
  provider_type: "供应商类型",
  provider_count: "供应商数",
  channel_name: "通道",
  proxy_name: "代理",
  proxy_protocol: "协议",
  proxy_url: "代理地址",
  exit_ip: "出口 IP",
  country: "国家",
  country_code: "国家代码",
  region: "地区",
  city: "城市",
  account_count: "账号数",
  channel_count: "通道数",
  last_test_status: "最近检测",
  last_test_latency_ms: "检测耗时 ms",
  last_test_error: "检测错误",
  last_tested_at: "检测时间",
  last_upstream_status: "上游状态码",
  quality_grade: "质量等级",
  quality_summary: "质量摘要",
  quality_problem: "质量原因",
  quality_checked_at: "质量检测时间",
  target: "目标",
  http_status: "HTTP 状态",
  cf_ray: "CF Ray",
  last_model_sync_status: "模型同步",
  last_model_sync_error: "同步错误",
  last_model_sync_at: "同步时间",
  owner: "归属",
  pool_group: "号池分组",
  route_tags: "路由标签",
  default_route_tags: "默认路由标签",
  default_metadata: "默认元数据",
  pool_groups: "号池分组",
  quota_summary: "配额汇总",
  quota_windows: "配额窗口",
  template: "模板",
  template_label: "模板",
  credential_present: "凭证",
  has_auth_state: "认证状态记录",
  valid: "有效",
  errors: "错误",
  warnings: "警告",
  last_quota_status: "最近额度刷新",
  last_quota_error: "额度错误",
  last_quota_at: "额度刷新时间",
  auth_expires_at: "认证过期",
  concurrency: "并发",
  active_requests: "当前请求",
  max_concurrency: "最大并发",
  circuit_state: "熔断状态",
  runtime_last_error: "运行错误",
  eligible: "可用",
  excluded_reasons: "排除原因",
  headroom_score: "余量分",
  failure_penalty: "失败惩罚",
  quota_reset_at: "配额重置",
  account_name: "账号",
  account_status: "账号状态",
  snapshot_id: "快照 ID",
  quality_status: "质量状态",
  quality_score: "质量分",
  availability_score: "可用性分",
  latency_score: "延迟分",
  quota_score: "额度分",
  error_score: "错误分",
  decision: "处置建议",
  reason_summary: "原因",
  reason: "原因",
  reasons: "原因",
  previous_status: "原状态",
  next_status: "新状态",
  actor_user_id: "操作者",
  actor_type: "操作者类型",
  action: "动作",
  ip_address: "IP",
  secret_key_configured: "Secret Key",
  webhook_secret_configured: "Webhook Secret",
  secret_key_source: "Secret 来源",
  webhook_secret_source: "Webhook 来源",
  success_url: "成功 URL",
  cancel_url: "取消 URL",
  success_url_source: "成功 URL 来源",
  cancel_url_source: "取消 URL 来源",
  mode: "模式",
  metrics: "指标明细",
  metadata: "元数据",
  type_or_url: "类型/地址",
  provider_id: "供应商 ID",
  client_type: "客户端类型",
  account_id: "账号 ID",
  window_type: "窗口类型",
  remaining: "剩余",
  limit_value: "总额度",
  reset_at: "重置时间",
  source: "来源",
  refresh_job_id: "刷新任务 ID",
  trigger_type: "触发方式",
  total_count: "总数",
  success_count: "成功数",
  failed_count: "失败数",
  skipped_count: "跳过数",
  unsupported_count: "不支持数",
  target_path: "目标路径",
  scheduled_for: "计划时间",
  failed_quota_refresh: "额度失败",
  unsupported_quota_refresh: "额度不支持",
  health_enabled: "健康检测",
  quota_refresh_enabled: "额度刷新",
  wakeup_enabled: "唤醒任务",
  health_interval_seconds: "检测间隔秒",
  quota_refresh_interval_seconds: "额度间隔秒",
  wakeup_interval_seconds: "唤醒间隔秒",
  quota_low_threshold_percent: "低额度阈值 %",
  max_failure_count: "最大失败次数",
  base_url: "基础地址",
  priority: "优先级",
  weight: "权重",
  timeout_seconds: "超时秒数",
  routing_mode: "路由模式",
  owner_user_id: "所属用户 ID",
  auth: "认证",
  runtime: "运行时",
  auth_mode: "认证模式",
  auth_status: "认证状态",
  provider_subject: "供应商主体",
  refresh_due_at: "应刷新时间",
  last_error: "最后错误",
  job_type: "任务类型",
  channel_id: "通道 ID",
  discovered_count: "发现数",
  updated_count: "更新数",
  started_at: "开始时间",
  finished_at: "完成时间",
  requested_by: "请求人",
  oauth_progress: "授权进度",
  attempt_count: "尝试次数",
  max_attempts: "最大尝试",
  lease_owner: "租约持有者",
  request_id: "请求 ID",
  dimension: "维度",
  group_by: "分组",
  requested_model: "请求模型",
  upstream_model: "上游模型",
  endpoint: "端点",
  input_tokens: "输入 tokens",
  output_tokens: "输出 tokens",
  image_count: "图片数",
  request_count: "请求数",
  actual_cost: "实际成本",
  rejected_count: "拒绝数",
  metered_request_count: "计量请求数",
  stream_event_count: "流事件数",
  websocket_frame_count: "WebSocket 帧数",
  rule_name: "规则",
  binding_count: "绑定数",
  active_count: "活跃数",
  expired_count: "过期数",
  total_hits: "命中数",
  total_misses: "未命中数",
  last_seen_at: "最后看到",
  last_hit_at: "最后命中",
  last_miss_at: "最后未命中",
  upstream_status: "上游状态",
  duration_ms: "耗时 ms",
  usage_source: "计量来源",
  test_type: "检测类型",
  target_url: "目标 URL",
  latency_ms: "耗时 ms",
  error_message: "错误信息",
  tested_at: "检测时间",
  conflict_type: "冲突类型",
  alias: "别名",
  detail: "详情",
  target_type: "目标类型",
  target_id: "目标 ID",
  daily_usd_limit: "每日 USD 限制",
  monthly_usd_limit: "每月 USD 限制",
  daily_request_limit: "每日请求限制",
  monthly_request_limit: "每月请求限制",
  low_balance_threshold: "低余额阈值",
  order_type: "订单类型",
  plan_id: "计划 ID",
  stripe_checkout_session_id: "Stripe Checkout",
  stripe_payment_intent_id: "Stripe PaymentIntent",
  stripe_subscription_id: "Stripe 订阅",
  stripe_refund_id: "Stripe 退款",
  payment_provider: "支付服务商",
  payment_method: "支付方式",
  provider_instance_id: "服务商实例",
  pay_currency: "实付币种",
  pay_amount_cents: "实付分",
  fx_rate: "汇率",
  upstream_trade_no: "上游订单号",
  upstream_transaction_id: "上游交易号",
  checkout_url: "Checkout URL",
  paid_at: "支付时间",
  refunded_at: "退款时间",
  refund_blocked_reason: "退款阻塞原因",
  price_usd: "价格 USD",
  billing_period: "周期",
  wallet_credit_usd: "赠送余额",
  group_id: "分组 ID",
  group_name: "分组",
  stripe_price_id: "Stripe Price",
  features: "功能",
  plan_name: "计划",
  granted_group_id: "授予分组",
  current_period_start: "当前周期开始",
  current_period_end: "当前周期结束",
  code: "邀请码",
  rebate_rate: "返利比例",
  affiliate_code_id: "推广码 ID",
  settled_at: "结算时间",
  api_key_id: "API Key ID",
  rule_id: "规则 ID",
  matched_value: "命中内容",
  channel_type: "通道类型",
  min_severity: "最低级别",
  event_types: "事件类型",
  signing_secret_present: "签名密钥",
  target_url_present: "Webhook 地址",
  provider_event_id: "事件 ID",
  provider: "提供方",
  order_id: "订单 ID",
  event_type: "事件类型",
  processed_at: "处理时间",
  processing_error: "处理错误",
  last_attempt_at: "最近尝试",
  next_attempt_at: "下次尝试",
  severity: "级别",
  title: "标题",
  message: "消息",
  payload: "载荷",
  body: "正文",
  audience: "受众",
  starts_at: "开始时间",
  ends_at: "结束时间",
  slug: "Slug",
  page_type: "页面类型",
  setting_key: "设置键",
  category: "分类",
  is_public: "公开",
  updated_by: "更新人",
  model_multiplier: "模型倍率",
  rpm_limit: "RPM 限制",
  members: "成员",
  permissions: "模型权限",
  abnormal_accounts: "异常账号",
  rule_type: "规则类型",
  pattern: "匹配内容",
  attempts: "尝试次数",
  active_accounts: "可用账号",
  total_accounts: "账号总数",
  model: "模型",
  method: "方法",
  path: "路径",
  family: "类型",
  job_status: "任务状态",
};

const valueLabels: Record<string, string> = {
  user: "用户",
  api_key: "API 密钥",
  personal_user: "普通用户",
  operator: "操作员",
  platform_owner: "平台所有者",
  credit: "入账",
  debit: "扣款",
  adjustment: "调整",
  payment: "支付入账",
  subscription_credit: "订阅赠额",
  refund_reversal: "退款回冲",
  affiliate_rebate: "推广返利",
  wallet_topup: "钱包充值",
  subscription: "订阅",
  paid: "已支付",
  refunded: "已退款",
  refund_blocked: "退款阻塞",
  manual_quality_action: "手动质量处置",
  quality_recompute: "质量评分",
  restore: "恢复",
  settled: "已结算",
  unsupported: "不支持",
  scheduled: "定时",
  manual: "手动",
  metadata: "元数据",
  endpoint: "接口",
  month: "月",
  year: "年",
  one_time: "一次性",
  pool: "共享池",
  byo: "自带账号池",
  info: "信息",
  warning: "警告",
  critical: "严重",
  onboarding: "初始化",
  refresh: "刷新",
  reauth: "重新授权",
  revoke: "撤销",
  oauth: "OAuth",
  codex_cli: "Codex CLI",
  draft: "草稿",
  published: "已发布",
  archived: "已归档",
  all: "全部",
  portal: "用户侧",
  admin: "管理侧",
  allow: "允许",
  deny: "拒绝",
  flag: "标记",
  block: "阻断",
  throttle: "限速",
  sensitive_word: "敏感词",
  ssrf_target: "目标限制",
  request_limit: "请求限制",
  bot_protection: "Bot 防护",
  abuse_pattern: "异常模式",
  requests: "请求数",
  tokens: "Tokens",
  closed: "关闭",
  open: "开启",
  processed: "已处理",
  replayed: "已重放",
  healthy: "健康",
  degraded: "降级",
  isolated: "已隔离",
  watch: "观察",
  isolate: "隔离",
  warn: "告警",
  pass: "通过",
  challenge: "挑战",
  base_connectivity: "基础连通",
  custom: "自定义目标",
};

function columnLabel(column: string) {
  return columnLabels[column] ?? column;
}

function cell(value: unknown) {
  if (Array.isArray(value)) {
    if (!value.length) return "";
    if (value.some((item) => item && typeof item === "object")) {
      return <code className="cell-json">{JSON.stringify(value)}</code>;
    }
    return <span className="cell-list">{value.map((item) => String(item)).join(", ")}</span>;
  }
  if (value && typeof value === "object") return <code className="cell-json">{JSON.stringify(value)}</code>;
  if (typeof value === "boolean") return value ? "是" : "否";
  const text = String(value ?? "");
  if (isStatus(text)) return <StatusBadge status={text} />;
  if (text in valueLabels) return valueLabels[text];
  if (isMonoValue(text)) return <code>{text}</code>;
  return text;
}

function isStatus(value: string) {
  return [
    "active",
    "disabled",
    "pending",
    "processed",
    "replayed",
    "paid",
    "refunded",
    "refund_blocked",
    "settled",
    "draft",
    "archived",
    "published",
    "success",
    "succeeded",
    "failed",
    "running",
    "rejected",
    "queued",
    "leased",
    "canceled",
    "revoked",
    "expired",
    "refresh_due",
    "reauth_required",
    "cooldown",
    "half_open",
    "half-open",
    "circuit_open",
    "circuit-open",
    "exhausted",
    "healthy",
    "warn",
    "pass",
    "challenge",
  ].includes(value);
}

function isMonoValue(value: string) {
  return /^(req_|rk_|sk-|[a-f0-9-]{12,}|https?:\/\/|\d{4}-\d{2}-\d{2}|[\w.-]+\/[\w.-]+$)/i.test(value);
}

function StatusBadge({ status }: { status: string }) {
  const normalized = status.replace(/_/g, "-").toLowerCase();
  return (
    <span className={`status-badge ${normalized}`}>
      <span />
      {statusLabel(status)}
    </span>
  );
}

function statusLabel(status: string) {
  const labels: Record<string, string> = {
    active: "启用",
    disabled: "停用",
    pending: "待处理",
    processed: "已处理",
    replayed: "已重放",
    paid: "已支付",
    refunded: "已退款",
    refund_blocked: "退款阻塞",
    settled: "已结算",
    draft: "草稿",
    archived: "已归档",
    published: "已发布",
    success: "成功",
    succeeded: "成功",
    failed: "失败",
    running: "运行中",
    rejected: "已拒绝",
    queued: "排队中",
    leased: "执行中",
    canceled: "已取消",
    revoked: "已撤销",
    expired: "已过期",
    refresh_due: "待刷新",
    reauth_required: "需重新授权",
    cooldown: "冷却中",
    half_open: "半开",
    "half-open": "半开",
    circuit_open: "熔断开启",
    "circuit-open": "熔断开启",
    exhausted: "已耗尽",
    healthy: "健康",
    warn: "告警",
    pass: "通过",
    challenge: "挑战",
  };
  return labels[status] ?? status;
}
